'use client'
import Head from 'next/head'
import { BiUserPlus } from 'react-icons/bi'
import Table from './components/table'
import Form from './components/form'
import {useState} from 'react'


export default function Home() {

  const[visible, setVisible]= useState(false)

  const handler=()=>{
    setVisible(!visible)
  }

  return (
    <section className='bg-#cfb53b'>
      <Head className="bg-yellow-400 text-gray-800">
        <title>Employee Application </title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
    
    <main className='py-5'>
      <h1 className='text-xl md:text-5xl text-center font bold py-10 bg-yellow text-yellow-400'> SMART SHIFT </h1>

       
    <div className='container mx-auto flex justify-between py-5 border-b'>
      <div className='left flex gap-3'>
        <button onClick={handler} className='flex bg-yellow-500 text-gray-800 px-4 py-2 border rounded-md hover:bg-gray-75 hover: border-yellow-500 hover:text-gray-100'>
          Add Employee  <span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
          </button>
      </div>
   

    </div>

       {/*collapsable form*/}
       
          {visible ? <Form></Form>: <></>}  
       
        
        {/*table*/}
      <div className='container mx-auto'>
        <Table></Table></div>

      </main>
    </section>
  )
}
